spring.application.name=discovery-server

# Eureka server port
server.port=8761

# This service is the Eureka server, so it should not register itself as a client.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
